#!/bin/bash

#SBATCH -p gpu-preempt # Submit job to gpu-preempt partition
#SBATCH -t 23:00:00 # Set max job time for 23 hours
#SBATCH --ntasks=1 # Set the number of tasks to 1
#SBATCH --gpus-per-task=1 # Request 1 GPU per task
#SBATCH --constraint=m40 # Request access to a 2080ti GPU
#SBATCH --mem=30G # Request 30GB of memory
#SBATCH --array=0-99 # Set the array size to 100
#SBATCH --output=logs/slurm-%A_%a.out # Specify the output log file
#SBATCH --error=logs/slurm-%A_%a.err # Specify the error log file

# Activate the conda environment
module load miniconda/22.11.1-1
conda activate control

# Set the input and output data paths
input_data_dir="/project/pi_ekalogerakis_umass_edu/dshivashok/ControlNet/data/03001627_pointbert_100_depth"
output_data_dir="/project/pi_ekalogerakis_umass_edu/dshivashok/ControlNet/data/03001627_pointbert_100_controlnet_inpainting_0.6_final"

# Array of foreground prompts
# foreground_prompts=(
# "A regal throne chair with ornate gold detailing"
# "A sleek office chair in modern white"
# "A cozy armchair with plush red upholstery"
# "A rustic rocking chair in warm, natural wood"
# "An elegant dining chair with rich, carved mahogany"
# "A classic wingback chair in polished brown leather"
# "A simple wooden chair with a minimalist design"
# "A luxurious accent chair in deep, tufted velvet"
# "A whimsical child's chair with playful, painted animals"
# "An industrial stool in raw, brushed metal"
# "A traditional easy chair in soft, muted green"
# "A sleek lounge chair in futuristic silver"
# "A shabby-chic chair with distressed white paint"
# "A mid-century modern chair in rich, walnut wood"
# "A grand library chair in deep, burgundy leather"
# "An art deco-inspired chair in elegant, curved lines"
# "A rustic Adirondack chair in weathered, gray wood"
# "A classic Windsor chair in traditional, black finish"
# "A modern plastic chair in sleek, white form"
# "A cozy rocking chair with soft, knit upholstery"
# "A sleek cantilever chair in polished chrome"
# "A traditional armchair in regal, Queen Anne style"
# "A bohemian hanging chair with intricate, woven details"
# "A modern office stool in sleek, black design"
# "A rustic log chair with natural, bark accents"
# "An elegant fauteuil chair in rich, gold leaf"
# "A retro bucket seat in bright, swivel yellow"
# "A classic Mission-style chair in sturdy, oak wood"
# "A luxurious chaise lounge in plush, navy velvet"
# "A playful children's chair in bright, primary colors"
# "An industrial drafting stool in brushed, metal finish"
# "A traditional dining chair in ornate, Chippendale style"
# "A modern wire mesh chair in geometric, silver design"
# "An elegant accent chair in rich, nailhead trim"
# "A rustic twig chair with natural, woven seat"
# "A mid-century modern lounge chair in sleek, black leather"
# "A traditional ladder-back chair with simple, rush seat"
# "A sleek ghost chair in transparent, acrylic design"
# "A bohemian papasan chair with intricate, rattan frame"
# "A modern kneeling chair in ergonomic, black design"
# "A rustic armchair in natural, cowhide upholstery"
# "An elegant settee in tufted, cream velvet"
# "A classic rocking chair in traditional, Shaker style"
# "A luxurious recliner in overstuffed, brown leather"
# "An industrial bar stool with reclaimed, wood seat"
# "A traditional armchair in ornate, bergère style"
# "A modern stacking chair in sleek, red plastic"
# "An elegant dining chair with ornate, carved details"
# "A rustic rocking chair in bent, natural wood"
# "A mid-century modern hanging chair in rich, teal color"
# "A traditional library chair in tufted, brown leather"
# "A sleek gaming chair in ergonomic, black design"
# "A bohemian hammock chair with colorful, fringe details"
# "A modern futon chair in sleek, gray upholstery"
# "A rustic bench in rough-hewn, natural wood"
# "An elegant slipper chair in soft, velvet pink"
# "A classic Adirondack chair in traditional, white wood"
# "A luxurious ottoman in tufted, emerald green"
# "An industrial folding chair in distressed, metal patina"
# "A traditional armchair in classic, Morris style"
# "A modern balance ball chair in sleek, black design"
# "An elegant wingback chair in ornate, Queen Anne style"
# "A rustic rocker in natural, hickory wood"
# "A mid-century modern accent chair in bold, red color"
# "A traditional writing chair in classic, Windsor style"
# "A sleek recliner in modern, zero gravity design"
# "A bohemian hanging chair in natural, woven rattan"
# "A modern sleeper chair in sleek, gray fabric"
# "A rustic barstool in natural, saddle-shaped leather"
# "An elegant lady's chair in Victorian, brocade upholstery"
# "A playful toddler chair in bright, primary colors"
# "A classic club chair in tufted, brown leather"
# "A luxurious massage chair in sleek, black design"
# "An industrial piano stool in adjustable, metal design"
# "A traditional armchair in classic, Chesterfield style"
# "A modern rocking chair in sleek, molded plywood"
# "An elegant side chair in rich, Louis XVI style"
# "A rustic stool in natural, wood design"
# "A mid-century modern chair in wire, chrome finish"
# "A traditional rocking chair in classic, spindle style"
# "A sleek office chair in modern, mesh black"
# "A bohemian floor cushion in colorful, embroidered fabric"
# "A modern hanging chair in sleek, white design"
# "A rustic armchair in reclaimed, barn wood finish"
# "An elegant armchair in flowing, curved lines"
# "A playful child's chair in bright, vibrant colors"
# "A classic dining chair in traditional, mahogany finish"
# "A luxurious lounge chair in rich, black leather"
# "An industrial stool in raw, steel finish"
# "A traditional rocking chair in classic, wicker design"
# "A sleek accent chair in modern, chrome base"
# "A bohemian swing chair in natural, woven bamboo"
# "A modern task chair in ergonomic, gray design"
# "A rustic dining chair in natural, pine wood"
# "An elegant armchair in rich, velvet burgundy"
# "A playful rocking chair in bright, rainbow colors"
# "A classic wingback chair in traditional, plaid fabric"
# "A luxurious chaise lounge in plush, white leather"
# "An industrial drafting chair in sleek, black design"
# "A traditional side chair in ornate, hand-carved details"
# "A sleek lounge chair in modern, stainless steel"
# "A bohemian hanging chair in colorful, macrame design"
# )


foreground_prompts=(
  "Chair outlined with a glowing neon light"
  "Soft shadow play across the chair from a nearby window"
  "Reflective gloss finish applied to the chair surface"
  "Chair cast in a single dramatic spotlight"
  "Gradient color wash painted on the chair"
  "Chair silhouette against a brightly lit background"
  "Textured sandblast effect on the chair's legs"
  "Frosting effect on the chair, mimicking ice crystals"
  "Chair wrapped in a thin, translucent shroud"
  "Rustic patina effect to give the chair an aged look"
  "Chair painted in a matte black ultra-modern finish"
  "Soft pastel tones brushed onto the chair"
  "Chair with a chrome mirror finish for a sleek look"
  "Glowing outline tracing the chair's contours in the dark"
  "Chair textured with a marble-like veneer"
  "Chair detailed with small, intricate mandala patterns"
  "Chair appearing as a watercolor painting with blurred edges"
  "Gold leaf accents highlighting the chair's design features"
  "Chair with a distressed leather visual effect"
  "Chair enhanced with a holographic shimmer effect"
  "Dappled light effect on the chair simulating sunlight through leaves"
  "Chair with a luminous pearlescent coating"
  "Chair edges accentuated with a bold, graphic line art"
  "Chair with an ombre effect transitioning from top to bottom"
  "Minimalist white outline on a dark chair for contrast"
  "Chair with a stucco texture for a Mediterranean feel"
  "Chair depicted in a low-poly, geometric art style"
  "Chair with a vintage sepia tone effect"
  "Chair covered in a delicate floral lace pattern"
  "Chair with a psychedelic tie-dye effect"
  "Chair with a digital pixelated mosaic effect"
  "Iridescent bubbles surrounding the chair, creating a magical aura"
  "Chair with a ghostly semi-transparent appearance"
  "Chair appearing to dissolve into a cloud of smoke at the base"
  "Laser-etched tribal patterns along the chair's sides"
  "Chair with a fluorescent glow under black light"
  "Flickering flame effect around the chair's edges"
  "Chair surrounded by a swirling vortex of autumn leaves"
  "Chair appearing to be made from crystalline ice"
  "Dynamic swirls of paint animating around the chair"
  "Chair with an effect of being underwater, complete with ripples"
  "Chair with a vintage crackle glaze finish"
  "Chair enclosed in a shimmering soap bubble"
  "Chair with a Sgraffito scratchwork revealing underlying colors"
  "Chair that appears to be woven from light fibers"
  "Chair with a radiant sunburst pattern emanating from the center"
  "Chair that looks as if it is phasing in and out of reality"
  "Chair with an organic mossy growth texture"
  "Chair appearing to be crafted from old, weathered driftwood"
  "Chair with an animated aura of falling snowflakes"
  "Chair that seems to cast multiple shadows in different colors"
  "Chair with a lace-like shadow pattern on the floor around it"
  "Chair that changes colors based on the viewing angle"
  "Chair bathed in the glow of a rising or setting sun"
  "Chair with a subtle embossed leather effect"
  "Chair with swirling Van Gogh-style brushstrokes"
  "Chair depicted as if sketched with charcoal and smudges"
  "Chair surrounded by a halo of twinkling fireflies"
  "Chair casting a long, dramatic shadow to suggest evening light"
  "Chair with a silhouette filled with a starry night sky"
  "Chair appearing to be wrapped in flowing silk ribbons"
  "Chair with a dynamic explosion of color splashes behind it"
  "Chair casting a shadow that morphs into abstract shapes" 
  "Chair surrounded by a mist of golden sparkles"
  "Chair with a monochrome palette except for one vivid color"
  "Chair covered in a digital glitch art effect"
  "Chair with shadows that subtly shift as if alive"
  "Chair appearing as if painted by quick, impressionist strokes"
  "Chair with an aura that pulsates softly"
  "Chair that casts a floral patterned shadow"
  "Chair with a dripping paint effect from the edges"
  "Chair enveloped in a soft, dreamy fog"
  "Chair with edges that glow as if backlit"
  "Chair with a dynamic wind-blown sand effect at its base"
  "Chair casting a shadow with the silhouette of a different object"
  "Chair that looks as if it's melting into the floor"
  "Chair with a projection of old film reels playing across it"
  "Chair surrounded by a rotating orbit of small, luminescent particles"
  "Chair with a surreal mirror effect on its surface"
  "Chair outlined with tiny sparkling LEDs"
  "Chair with an ancient stone texture, like an archaeological find"
  "Chair that appears to be part of a watercolor landscape"
  "Chair with a cascading waterfall effect from the seat"
  "Chair with an optical illusion that makes it seem invisible from certain angles"
  "Chair with a shadow that appears as if in watercolor"
  "Chair with a frost pattern creeping over its surface"
  "Chair with a shadow that tells a different story (like a scene from nature)"
  "Chair appearing to be made from swirling autumn winds"
  "Chair that seems to be breaking into digital pixels at one edge"
  "Chair with an oil slick, iridescent finish"
  "Chair enveloped in a soft halo of blue light"
  "Chair with a chalk outline effect on the ground around it"
  "Chair with a thermal heat map color effect"
  "Chair with elegant Art Nouveau style floral patterns etched into it"
  "Chair surrounded by a static electricity effect"
  "Chair with an echo effect, multiple faint outlines radiating out"
  "Chair with an exaggerated, cartoon-like outline"
  "Chair with a soft pastel gradient wash over it"
  "Chair that appears to be slowly rotating on its axis"
  "Chair with a gentle, pulsing bioluminescent glow from within"
)

# Array of background prompts
# background_prompts=(
#   "Antique bookshop with cozy reading nooks" 
#   "White sand beach with sunset horizon"
#   "Urban rooftop garden with city skyline"
#   "Dimly lit vintage jazz club"
#   "Rainforest with vibrant, lush foliage"
#   "Old-fashioned train station platform"
#   "Sleek modern office with glass walls"
#   "Art deco theater with ornate details"
#   "Snowy mountain lodge with fireplace"
#   "Underwater coral reef with colorful fish"
#   "Misty Japanese Zen garden at dawn"
#   "Blooming cherry orchard in spring"
#   "Moonlit Gothic cathedral ruins" 
#   "Sun-drenched Tuscan vineyard"
#   "Northern lights over icy landscape"
#   "Busy Moroccan bazaar with vibrant textiles"
#   "Futuristic cityscape with neon lights"
#   "Old Western ghost town at dusk"
#   "Brightly lit 1950s diner at night"
#   "Quiet library with towering bookcases"
#   "Desert oasis with palm trees"
#   "Luxurious Victorian drawing room"
#   "Abandoned amusement park with rusty rides"
#   "Contemporary artist loft with large windows"
#   "Calm lakeside with misty morning fog"
#   "Sumptuous French chateau garden"
#   "Enchanted forest with glowing mushrooms"
#   "Colorful Caribbean town with pastel houses"
#   "Steampunk workshop with brass gadgets"
#   "Vivid autumn forest with fallen leaves"
#   "Lush bamboo forest with filtered sunlight"
#   "Busy New York street with skyscrapers"
#   "Artisan pottery studio with clay pots"
#   "Serene monastery courtyard with monks"
#   "Baroque palace ballroom with golden ornaments"
#   "Sunny coastal boardwalk with seagulls"
#   "Quiet suburban backyard at twilight"
#   "Decrepit industrial warehouse with graffiti"
#   "Bright pop art gallery with bold colors"
#   "Mysterious swamp with fog and willows"
#   "Retro 1960s living room with geometric patterns"
#   "Minimalist Scandinavian kitchen with natural wood"
#   "Warm Moroccan patio with mosaic tiles"
#   "Cramped antique shop with stacked books"
#   "Snow-covered bridge in a winter park"
#   "Opulent opera house with red velvet curtains"
#   "Rustic mountain path with autumn leaves"
#   "Sundrenched vine-covered pergola"
#   "Night market with lanterns and stalls"
#   "High-tech control room with glowing panels"
#   "Quiet seaside pier at sunset"
#   "Old Parisian café with cobblestone street"
#   "Sleek Silicon Valley tech startup office"
#   "Dim speakeasy with vintage furnishings"
#   "Bustling Tokyo intersection at night"
#   "Frozen lake with distant snow-capped mountains"
#   "Historic London pub with wood paneling"
#   "Tropical rainforest waterfall with exotic birds"
#   "Gleaming futuristic airport terminal"
#   "Quaint English garden with blooming roses"
#   "Vibrant Rio carnival with dancers"
#   "Spooky forest path with twisted trees"
#   "Classic car show with 1950s automobiles"
#   "Luxury yacht deck with open ocean view"
#   "Old world map room with globes and artifacts"
#   "Bright circus tent with colorful stripes"
#   "Lavender field at sunrise with bees buzzing"
#   "Elegant wedding tent with string lights"
#   "Deserted beach at dawn with soft waves"
#   "Active volcano with flowing lava"
#   "Sunset over a sprawling vineyard"
#   "Abandoned lighthouse on a rocky shore"
#   "Modern observatory under starry skies"
#   "Lively street fair with colorful banners"
#   "Quiet reading nook with stacks of books"
#   "Serene Alpine meadow with wildflowers"
#   "Historic train car with plush seating"
#   "Eerie graveyard with fog and full moon"
#   "Quirky bookstore with ladders and alcoves"
#   "Classic barbershop with red leather chairs"
#   "Airy botanical greenhouse with hanging plants"
#   "Cliffside view over a turbulent sea"
#   "Old-fashioned classroom with chalkboard"
#   "Artistic mural alley with vibrant graffiti"
#   "Elegant tea room with fine china"
#   "Underground cave with stalactites and stalagmites"
#   "Bustling farmers market with fresh produce"
#   "Regal castle throne room with tapestries"
#   "Secluded pond with a wooden dock"
#   "Carnival at night with lit Ferris wheel"
#   "Ancient temple ruins overgrown with ivy"
#   "Hip co-working space with modern decor"
#   "Sandy desert at twilight with cactus silhouettes"
#   "Quaint cobblestone alley in a European village"
#   "Dynamic skate park with ramps and rails"
#   "Cozy ski lodge with a roaring fire"
#   "Turbulent storm at sea with crashing waves"
#   "Retro drive-in theater with vintage cars"
#   "Lush orchid conservatory with glass ceilings"
#   "Snowy city park with children sledding"
# )

background_prompts=(
"A cozy living room with warm, inviting earth tones"
"A sleek, modern office with minimalist white and gray decor" 
"A rustic, countryside kitchen with rich, wooden accents"
"A serene, tranquil bedroom with soft, pastel lighting"
"A vibrant, colorful playroom with cheerful, bright walls"
"A sophisticated, elegant dining room with a sparkling chandelier"
"A charming, quaint coffee shop with exposed brick walls"
"A luxurious, opulent hotel lobby with gleaming marble floors" 
"A bright, airy sunroom with large windows and natural hues"
"A comfy, welcoming home theater with plush, dark carpet"
"A tidy, organized home office with neutral, calming tones"
"A whimsical, enchanting child's bedroom with colorful, painted murals"
"A classic, traditional library with rich, dark wood paneling"
"A chic, stylish dressing room with full-length mirrors and soft lighting"
"A peaceful, calming yoga studio with natural light and earthy colors"
"A funky, retro game room with bright neon lights"
"An industrial, loft-style living space with exposed brick and metal accents"
"A cozy, intimate reading nook with built-in bookshelves and warm lighting"
"A bright, cheery breakfast nook with large windows and vibrant colors"
"A formal, stately conference room with dark, paneled walls"
"A warm, inviting foyer with a grand staircase and rich, wood tones"
"A relaxing, spa-like bathroom with soothing, muted colors"
"A cool, contemporary art studio with high ceilings and bright, white walls"
"A rustic, outdoor patio with natural stone pavers"
"A homey, comfortable family room with a fireplace and warm, earthy hues"
"A sleek, high-tech computer lab with modern furniture and cool, blue tones"
"A charming, old-fashioned parlor with antique decor and soft, vintage colors"
"A bright, open-concept kitchen with white cabinets and natural light"
"A regal, majestic throne room with ornate details and rich, royal hues"
"A serene, Japanese-inspired meditation room with shoji screens and natural wood tones"
"A fun, lively recreation room with a pool table and bright, energetic colors"
"A sophisticated, upscale restaurant with dim lighting and rich, dark accents"
"A cozy, rustic cabin living room with log walls and warm, earthy colors"
"A cheerful, inviting sunporch with wicker furniture and bright, sunny hues" 
"A sleek, futuristic spacecraft interior with metal surfaces and cool, blue lighting"
"A charming, vintage-inspired diner with checkered floors and bright, retro colors"
"A grand, imposing ballroom with crystal chandeliers and elegant, neutral tones"
"A peaceful, serene conservatory with glass walls and lush, green plants"
"A cozy, intimate wine cellar with brick walls and warm, amber lighting"
"A bright, colorful art gallery with white walls and vibrant, artistic accents"
"A rustic, charming barn interior with wooden beams and natural, earthy tones"
"A sophisticated, modern lecture hall with tiered seating and sleek, gray accents"
"A warm, welcoming waiting room with comfortable seating and soothing, neutral colors"
"A cool, industrial garage with concrete floors and bright, fluorescent lighting"
"A luxurious, elegant opera house with velvet curtains and rich, regal hues"
"A cozy, inviting ski lodge with a stone fireplace and warm, wooden accents"
"A bright, airy atrium with a glass roof and natural, green foliage"
"A sophisticated, upscale jazz club with dim lighting and deep, moody colors"
"A serene, peaceful garden gazebo with climbing vines and soft, natural hues"
"A charming, old-fashioned ice cream parlor with pastel colors and vintage accents"
"A grand, impressive university library with high ceilings and rich, scholarly tones"
"A cozy, intimate tea room with floral wallpaper and delicate, pastel colors"
"A sleek, modern airport lounge with large windows and cool, metallic accents"
"A rustic, charming farmhouse kitchen with a large island and warm, country hues"
"A bright, cheerful kindergarten classroom with colorful decor and vibrant accents" 
"A sophisticated, upscale cocktail lounge with plush seating and rich, dark tones"
"A peaceful, serene home yoga studio with natural light and calming, earthy colors"
"A cozy, inviting bed and breakfast parlor with antiques and soft, vintage hues"
"A grand, opulent palace ballroom with gold accents and regal, luxurious tones"
"A bright, open artist's studio with large windows and crisp, white walls"
"A rustic, charming mountain cabin with a wood stove and warm, natural colors"
"A sleek, modern corporate boardroom with glass walls and cool, professional hues"
"A cozy, intimate reading room with a fireplace and rich, inviting colors"
"A vibrant, colorful children's play area with soft flooring and bright, cheerful accents"
"A sophisticated, elegant theater green room with mirrors and dramatic, moody lighting"
"A peaceful, serene spa waiting area with a waterfall and soothing, natural tones"
"A bright, airy beach house living room with coastal decor and light, breezy hues"
"A grand, impressive hotel ballroom with a stage and elegant, neutral colors"
"A cozy, rustic hunting lodge with mounted trophies and warm, earthy tones"
"A sleek, modern science lab with stainless steel surfaces and bright, clinical lighting"
"A charming, old-fashioned barbershop with vintage decor and classic, masculine hues"
"A bright, colorful elementary school classroom with posters and vibrant, energetic accents"
"A sophisticated, upscale cigar lounge with leather seating and rich, dark colors"
"A peaceful, serene meditation garden with a koi pond and natural, calming tones"
"A cozy, intimate coffee house with local art and warm, inviting hues"
"A grand, opulent opera box with velvet curtains and luxurious, regal colors"
"A bright, open photography studio with white backdrops and crisp, clean lighting"
"A rustic, charming winery tasting room with oak barrels and warm, earthy tones"
"A sleek, modern dentist's office with exam chairs and cool, clinical colors"
"A cozy, inviting pub with dark wood paneling and warm, convivial lighting"
"A vibrant, colorful daycare playroom with kid-sized furniture and bright, cheerful hues"
"A sophisticated, elegant bridal suite with full-length mirrors and soft, romantic lighting"
"A peaceful, serene yoga retreat with mountain views and natural, earthy colors"
"A bright, airy solarium with potted plants and warm, sunny hues"
"A grand, impressive legislative chamber with a dais and rich, stately colors"
"A cozy, rustic ski chalet with a wood-burning stove and warm, inviting tones"
"A sleek, modern recording studio with soundproofing and cool, high-tech accents"  
"A charming, old-fashioned soda fountain with chrome stools and bright, retro colors"
"A bright, colorful preschool nap room with cots and soothing, pastel hues"
"A sophisticated, upscale members-only club with a bar and rich, exclusive tones"
"A peaceful, serene meditation room with floor cushions and calming, neutral colors"
"A cozy, intimate bookstore with overstuffed armchairs and warm, literary hues"
"A grand, opulent symphony hall with an orchestra pit and regal, luxurious accents"
"A bright, open dance studio with a mirrored wall and energetic, lively colors"
"A rustic, charming apple orchard with a picking basket and natural, earthy tones"
"A sleek, modern radiology lab with an MRI machine and cool, clinical hues"
"A cozy, inviting retirement home lounge with a piano and warm, comforting colors"
"A vibrant, colorful circus tent with a center ring and bold, exciting accents"
"A sophisticated, elegant charity gala with a silent auction and rich, glamorous tones" 
"A peaceful, serene church chapel with stained glass windows and soft, reverent hues"
)

# (
#   "Antique bookshop with cozy reading nooks with a chair in it" 
#   "White sand beach with sunset horizon with a chair in it"
#   "Urban rooftop garden with city skyline with a chair in it"
#   "Dimly lit vintage jazz club with a chair in it"
#   "Rainforest with vibrant, lush foliage with a chair in it"
#   "Old-fashioned train station platform with a chair in it"
#   "Sleek modern office with glass walls with a chair in it"
#   "Art deco theater with ornate details with a chair in it"
#   "Snowy mountain lodge with fireplace with a chair in it"
#   "Underwater coral reef with colorful fish with a chair in it"
#   "Misty Japanese Zen garden at dawn with a chair in it"
#   "Blooming cherry orchard in spring with a chair in it"
#   "Moonlit Gothic cathedral ruins with a chair in it" 
#   "Sun-drenched Tuscan vineyard with a chair in it"
#   "Northern lights over icy landscape with a chair in it"
#   "Busy Moroccan bazaar with vibrant textiles with a chair in it"
#   "Futuristic cityscape with neon lights with a chair in it"
#   "Old Western ghost town at dusk with a chair in it"
#   "Brightly lit 1950s diner at night with a chair in it"
#   "Quiet library with towering bookcases with a chair in it"
#   "Desert oasis with palm trees with a chair in it"
#   "Luxurious Victorian drawing room with a chair in it"
#   "Abandoned amusement park with rusty rides with a chair in it"
#   "Contemporary artist loft with large windows with a chair in it"
#   "Calm lakeside with misty morning fog with a chair in it"
#   "Sumptuous French chateau garden with a chair in it"
#   "Enchanted forest with glowing mushrooms with a chair in it"
#   "Colorful Caribbean town with pastel houses with a chair in it"
#   "Steampunk workshop with brass gadgets with a chair in it"
#   "Vivid autumn forest with fallen leaves with a chair in it"
#   "Lush bamboo forest with filtered sunlight with a chair in it"
#   "Busy New York street with skyscrapers with a chair in it"
#   "Artisan pottery studio with clay pots with a chair in it"
#   "Serene monastery courtyard with monks with a chair in it"
#   "Baroque palace ballroom with golden ornaments with a chair in it"
#   "Sunny coastal boardwalk with seagulls with a chair in it"
#   "Quiet suburban backyard at twilight with a chair in it"
#   "Decrepit industrial warehouse with graffiti with a chair in it"
#   "Bright pop art gallery with bold colors with a chair in it"
#   "Mysterious swamp with fog and willows with a chair in it"
#   "Retro 1960s living room with geometric patterns with a chair in it"
#   "Minimalist Scandinavian kitchen with natural wood with a chair in it"
#   "Warm Moroccan patio with mosaic tiles with a chair in it"
#   "Cramped antique shop with stacked books with a chair in it"
#   "Snow-covered bridge in a winter park with a chair in it"
#   "Opulent opera house with red velvet curtains with a chair in it"
#   "Rustic mountain path with autumn leaves with a chair in it"
#   "Sundrenched vine-covered pergola with a chair in it"
#   "Night market with lanterns and stalls with a chair in it"
#   "High-tech control room with glowing panels with a chair in it"
#   "Quiet seaside pier at sunset with a chair in it"
#   "Old Parisian café with cobblestone street with a chair in it"
#   "Sleek Silicon Valley tech startup office with a chair in it"
#   "Dim speakeasy with vintage furnishings with a chair in it"
#   "Bustling Tokyo intersection at night with a chair in it"
#   "Frozen lake with distant snow-capped mountains with a chair in it"
#   "Historic London pub with wood paneling with a chair in it"
#   "Tropical rainforest waterfall with exotic birds with a chair in it"
#   "Gleaming futuristic airport terminal with a chair in it"
#   "Quaint English garden with blooming roses with a chair in it"
#   "Vibrant Rio carnival with dancers with a chair in it"
#   "Spooky forest path with twisted trees with a chair in it"
#   "Classic car show with 1950s automobiles with a chair in it"
#   "Luxury yacht deck with open ocean view with a chair in it"
#   "Old world map room with globes and artifacts with a chair in it"
#   "Bright circus tent with colorful stripes with a chair in it"
#   "Lavender field at sunrise with bees buzzing with a chair in it"
#   "Elegant wedding tent with string lights with a chair in it"
#   "Deserted beach at dawn with soft waves with a chair in it"
#   "Active volcano with flowing lava with a chair in it"
#   "Sunset over a sprawling vineyard with a chair in it"
#   "Abandoned lighthouse on a rocky shore with a chair in it"
#   "Modern observatory under starry skies with a chair in it"
#   "Lively street fair with colorful banners with a chair in it"
#   "Quiet reading nook with stacks of books with a chair in it"
#   "Serene Alpine meadow with wildflowers with a chair in it"
#   "Historic train car with plush seating with a chair in it"
#   "Eerie graveyard with fog and full moon with a chair in it"
#   "Quirky bookstore with ladders and alcoves with a chair in it"
#   "Classic barbershop with red leather chairs with a chair in it"
#   "Airy botanical greenhouse with hanging plants with a chair in it"
#   "Cliffside view over a turbulent sea with a chair in it"
#   "Old-fashioned classroom with chalkboard with a chair in it"
#   "Artistic mural alley with vibrant graffiti with a chair in it"
#   "Elegant tea room with fine china with a chair in it"
#   "Underground cave with stalactites and stalagmites with a chair in it"
#   "Bustling farmers market with fresh produce with a chair in it"
#   "Regal castle throne room with tapestries with a chair in it"
#   "Secluded pond with a wooden dock with a chair in it"
#   "Carnival at night with lit Ferris wheel with a chair in it"
#   "Ancient temple ruins overgrown with ivy with a chair in it"
#   "Hip co-working space with modern decor with a chair in it"
#   "Sandy desert at twilight with cactus silhouettes with a chair in it"
#   "Quaint cobblestone alley in a European village with a chair in it"
#   "Dynamic skate park with ramps and rails with a chair in it"
#   "Cozy ski lodge with a roaring fire with a chair in it"
#   "Turbulent storm at sea with crashing waves with a chair in it"
#   "Retro drive-in theater with vintage cars with a chair in it"
#   "Lush orchid conservatory with glass ceilings with a chair in it"
#   "Snowy city park with children sledding with a chair in it"
# )

# Array of seeds
seed_range=10000

# Array of views
views=(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19)

# Get the list of model IDs
model_ids=($(ls -1 "${input_data_dir}" | grep -E '^[0-9]+_' | sort -u))

# Get the model ID for the current job
model_id="${model_ids[SLURM_ARRAY_TASK_ID]}"
echo "Processing depth maps for model ID: ${model_id}"

# Get the depth map path for the current job
depth_map_path="${input_data_dir}/${model_id}"

# Run the script with the specified arguments
python process_depth_inpainting_maps.py \
    --model_id "$model_id" \
    --depth_map_path "$depth_map_path" \
    --foreground_prompts "${foreground_prompts[@]}" \
    --background_prompts "${background_prompts[@]}" \
    --seed_range $seed_range \
    --views "${views[@]}" \
    --num_samples_per_model 50 \
    --num_foreground_steps 50 \
    --num_background_steps 100 \
    --image_resolution 512 \
    --control_strength 1.2 \
    --control_scale_guidance 9.0 \
    --inpaint_strength 0.6 \
    --output_data_dir "$output_data_dir"